language: go
go:
  - 1.8
go_import_path: github.com/meyskens/EduNav-backend/
addons:
  ssh_known_hosts: edunav.eyskens.me
  apt:
    packages:
        - sshpass

install:
  - export SSHPASS=$DEPLOY_PASS
  - go get -u github.com/labstack/echo
  - go get -u gopkg.in/mgo.v2

before_script:
  - go vet ./...

script:
  - sshpass -e ssh edunav@edunav.eyskens.me "echo ok";
  - GOOS=linux GOARCH=arm go build main.go

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: prod