language: go
go:
  - 1.8
go_import_path: github.com/meyskens/EduNav-backend/
addons:
  ssh_known_hosts: edunav.eyskens.me
  apt:
    packages:
        - sshpass

install:
  - export SSHPASS=$DEPLOY_PASS
  - go get -u github.com/labstack/echo
  - go get -u github.com/labstack/echo/middleware
  - go get -u gopkg.in/mgo.v2
  - go get -u github.com/google/go-github/github
  - go get -u github.com/patrickmn/go-cache

before_script:
  - go vet ./...

script:
  - sshpass -e ssh edunav@edunav.eyskens.me "echo ok";
  - GOOS=linux GOARCH=arm go build main.go

after_success:
- if [ "$TRAVIS_BRANCH" == "prod" ]; then sshpass -e ssh edunav@edunav.eyskens.me "sudo systemctl stop edunav" && sshpass -e scp ./main edunav@edunav.eyskens.me:/opt/edunav/ && sshpass -e ssh edunav@edunav.eyskens.me "sudo systemctl start edunav"; fi