language: go
go:
  - 1.x
go_import_path: github.com/meyskens/EduNav-backend/
env:
    global:
      - QEMU_VER=v2.9.1
      - DOCKER_REPO=maartje/edunav-backend
    matrix:
      - ARCH=amd64 GO_ARCH=amd64   QEMU_ARCH=x86_64
      - ARCH=armhf GO_ARCH=arm QEMU_ARCH=arm    
      - ARCH=arm64 GO_ARCH=arm64 QEMU_ARCH=aarch64

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo apt-get -y install qemu qemu-user-static qemu-user binfmt-support
  - docker run --rm --privileged multiarch/qemu-user-static:register


install:
  - go get -u github.com/labstack/echo
  - go get -u github.com/labstack/echo/middleware
  - go get -u gopkg.in/mgo.v2
  - go get -u github.com/google/go-github/github
  - go get -u github.com/patrickmn/go-cache
  - go get -u golang.org/x/oauth2

script:
  - GOOS=linux GOARCH="${GO_ARCH}" go build -o main main.go
  - docker build -t $DOCKER_REPO:$ARCH-latest --build-arg ARCH="$ARCH" ./

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push $DOCKER_REPO:$ARCH-latest ; fi